CODEOWNERS

Change from the default of "all lead engineers" ---> less spam in to mailboxes.

Change default reviewers

---

database/Dockerfile
database/schema.sql
docker-compose.yml

* Removes unnecessary database init config for postgres
* Exposes port 5432 for connecting to the dev database from outside docker
* Updates legacy docker compose `links` config to `depends_on`

Cleanup docker database configuration

---

BonusCalcApi/V1/Infrastructure/BonusCalcContext.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211031101646_DropIdentityFromPayElementTypes.Designer.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211031101646_DropIdentityFromPayElementTypes.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211031102001_DropIdentityFromSchemesAndPayBands.Designer.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211031102001_DropIdentityFromSchemesAndPayBands.cs

The pay element types and the pay bands are static data which we'll need to be able to refer from other systems so using generated values doesn't make sense. For example, the listener service will need to know the id for the relevant pay element type to create a productive entry in the pay elements table. I suggest we scope the types into three bandings based on current requirements:
```
1xx: Non-productive types such as dayworks and annual leave
2xx: Adjustments such as manual adjustments and balance brought forward
3xx: Productive types - initially reactive repairs but can be expanded
```
Similarly, the schemes and pay bands once setup should not change so I suggest the following numbering:
```
1: SMV scheme
2: Electrician
3: Plumber
4: Carpenter
5: Glazier
6: Gas Engineer
7: Roofer
8: …
```

Drop generated identity values for static data

---

BonusCalcApi.Tests/V1/Factories/ResponseFactoryTest.cs
BonusCalcApi.Tests/V1/Gateways/PayElementTypeGatewayTests.cs
BonusCalcApi.Tests/V1/Gateways/SummaryGatewayTests.cs
BonusCalcApi.Tests/V1/Gateways/TimesheetGatewayTests.cs
BonusCalcApi/V1/Boundary/Response/PayElementTypeResponse.cs
BonusCalcApi/V1/Factories/ResponseFactory.cs
BonusCalcApi/V1/Infrastructure/BonusCalcContext.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211110064800_AddOutOfHoursAndOvertimeFlags.Designer.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211110064800_AddOutOfHoursAndOvertimeFlags.cs
BonusCalcApi/V1/Infrastructure/PayElementType.cs

We need to be able to discern these pay element types them from other non-productive types to exclude them from bonus calculation as they are paid directly and don't earn SMVs.

Add 'out of hours' and 'overtime' flags

---

BonusCalcApi.Tests/V1/Factories/ResponseFactoryTest.cs
BonusCalcApi.Tests/V1/Gateways/PayElementTypeGatewayTests.cs
BonusCalcApi.Tests/V1/Gateways/SummaryGatewayTests.cs
BonusCalcApi.Tests/V1/Gateways/TimesheetGatewayTests.cs
BonusCalcApi/V1/Boundary/Response/PayElementTypeResponse.cs
BonusCalcApi/V1/Factories/ResponseFactory.cs
BonusCalcApi/V1/Infrastructure/BonusCalcContext.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211112171910_AddSelectableFlagToPayElementTypes.Designer.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211112171910_AddSelectableFlagToPayElementTypes.cs
BonusCalcApi/V1/Infrastructure/PayElementType.cs

This is to control what appears in the drop down boxes when pay elements are being edited in the frontend application.
Additionally marking adjustment pay elements as productive so that they appear in the summary reports. This allows us to use the 200-299 range for the 'Productive not in Repairs Hub' feature and keep the 300+ range for productive time coming from Repairs Hub.

Add a selectable flag to pay element types

---

BonusCalcApi.Tests/V1/E2ETests/OperativeTests.cs
BonusCalcApi.Tests/V1/Factories/DbFactoryTests.cs
BonusCalcApi.Tests/V1/Factories/ResponseFactoryTest.cs
BonusCalcApi.Tests/V1/Gateways/SummaryGatewayTests.cs
BonusCalcApi.Tests/V1/Gateways/TimesheetGatewayTests.cs
BonusCalcApi/V1/Boundary/Request/PayElementUpdate.cs
BonusCalcApi/V1/Boundary/Request/TimesheetUpdate.cs
BonusCalcApi/V1/Boundary/Response/PayElementResponse.cs
BonusCalcApi/V1/Boundary/Response/TimesheetResponse.cs
BonusCalcApi/V1/Factories/DbFactory.cs
BonusCalcApi/V1/Factories/ResponseFactory.cs
BonusCalcApi/V1/Infrastructure/BonusCalcContext.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211115174026_ConvertTimesheetIdToString.Designer.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211115174026_ConvertTimesheetIdToString.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211115191148_AddMissingIndexes.Designer.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211115191148_AddMissingIndexes.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211117115451_AddClosedAtToPayElements.Designer.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211117115451_AddClosedAtToPayElements.cs
BonusCalcApi/V1/Infrastructure/PayElement.cs
BonusCalcApi/V1/Infrastructure/Timesheet.cs

When importing data from Repairs Hub having to know the timesheet id to insert into pay elements adds overhead and makes it more difficult to reason with. By using a concatenation of operative id and week we can eliminate this.
@Asura5 this is a suggestion - when I was importing the data this morning I had to create a VLOOKUP column in Excel to a second sheet with the list of timesheet ids by operative id and being able to just do `123456/2021-01-11` would've saved a lot of effort. Also when viewing the pay elements table it's easier to see when a pay element is from as opposed to just a numeric id. On the downside it'll mean some work on LBHackney-IT/bonuscalc-listener#13 so I can understand if you'd prefer not to.

Convert timesheet id to a predictable string

---

BonusCalcApi.Tests/V1/Gateways/OperativeGatewayTest.cs
BonusCalcApi.Tests/V1/Gateways/SummaryGatewayTests.cs
BonusCalcApi.Tests/V1/Gateways/TimesheetGatewayTests.cs
BonusCalcApi.Tests/V1/Helpers/FixtureHelpers.cs
BonusCalcApi/V1/Boundary/Response/OperativeResponse.cs
BonusCalcApi/V1/Factories/ResponseFactory.cs
BonusCalcApi/V1/Infrastructure/BonusCalcContext.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211123165638_AddUtilisationToOperatives.Designer.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211123165638_AddUtilisationToOperatives.cs
BonusCalcApi/V1/Infrastructure/Operative.cs

This allows the frontend to adjust the pay bands to compensate for operatives that are employed on a part-time basis.

Add utilisation to operative endpoint

---

BonusCalcApi.Tests/V1/E2ETests/OperativeTests.cs
BonusCalcApi.Tests/V1/Gateways/SummaryGatewayTests.cs
BonusCalcApi.Tests/V1/UseCase/UpdateTimesheetUseCaseTests.cs
BonusCalcApi/V1/Boundary/Response/TimesheetResponse.cs
BonusCalcApi/V1/Boundary/Response/WeeklySummaryResponse.cs
BonusCalcApi/V1/Factories/ResponseFactory.cs
BonusCalcApi/V1/Infrastructure/BonusCalcContext.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211123182708_AddUtilisationToTimesheets.Designer.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211123182708_AddUtilisationToTimesheets.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211123184300_AddUtilisationToWeeklySummaries.Designer.cs
BonusCalcApi/V1/Infrastructure/Migrations/20211123184300_AddUtilisationToWeeklySummaries.cs
BonusCalcApi/V1/Infrastructure/Timesheet.cs
BonusCalcApi/V1/Infrastructure/WeeklySummary.cs

An operative may change from full-time to part-time or vice-versa during a bonus period so we need to track the utilisation week by week and then use an average utilisation over the whole period to work out the band.

Add utilisation to timesheet and weekly summaries

---

BonusCalcApi/V1/Infrastructure/Migrations/BonusCalcContextModelSnapshot.cs

These were missed off LBHackney-IT/bonuscalc-api#48 because EF would try to create a migration to insert the columns into the view - the workaround is to create a dummy migration afterwards to pick up the new properties on the view-backed models.

Include utilisation properties in the model snapshot

---

BonusCalcApi.Tests/V1/Controllers/OperativesControllerTests.cs
BonusCalcApi.Tests/V1/E2ETests/OperativeTests.cs
BonusCalcApi.Tests/V1/Factories/ResponseFactoryTest.cs
BonusCalcApi.Tests/V1/UseCase/UpdateReportSentAtUseCaseTests.cs
BonusCalcApi/Startup.cs
BonusCalcApi/V1/Boundary/Response/OperativeSummaryResponse.cs
BonusCalcApi/V1/Boundary/Response/TimesheetResponse.cs
BonusCalcApi/V1/Boundary/Response/WeeklySummaryResponse.cs
BonusCalcApi/V1/Controllers/OperativesController.cs
BonusCalcApi/V1/Factories/ResponseFactory.cs
BonusCalcApi/V1/Infrastructure/Migrations/20220103104934_AddReportSentAtToTimesheets.Designer.cs
BonusCalcApi/V1/Infrastructure/Migrations/20220103104934_AddReportSentAtToTimesheets.cs
BonusCalcApi/V1/Infrastructure/Migrations/20220103111915_AddReportSentAtToSummaryViews.Designer.cs
BonusCalcApi/V1/Infrastructure/Migrations/20220103111915_AddReportSentAtToSummaryViews.cs
BonusCalcApi/V1/Infrastructure/OperativeSummary.cs
BonusCalcApi/V1/Infrastructure/Timesheet.cs
BonusCalcApi/V1/Infrastructure/WeeklySummary.cs
BonusCalcApi/V1/UseCase/Interfaces/IUpdateReportSentAtUseCase.cs
BonusCalcApi/V1/UseCase/UpdateReportSentAtUseCase.cs

By recording when a report is sent and then updating the week closed_at once all operatives have a non-null report_sent_at then we can recover the week closing process in the middle should there be a failure like a browser being closed or crashing.
Similar to #56, this PR is based off an existing branch so it can be merged without needing to rebase when the previous PR is merged.

Record when the report was sent for an operative

---

BonusCalcApi.Tests/V1/Controllers/WeeksControllerTests.cs
BonusCalcApi.Tests/V1/E2ETests/WeekTests.cs
BonusCalcApi.Tests/V1/UseCase/UpdateReportsSentAtUseCaseTests.cs
BonusCalcApi/Startup.cs
BonusCalcApi/V1/Boundary/Response/WeekResponse.cs
BonusCalcApi/V1/Controllers/WeeksController.cs
BonusCalcApi/V1/Factories/ResponseFactory.cs
BonusCalcApi/V1/Infrastructure/Migrations/20220116175708_AddReportsSentAtToWeek.Designer.cs
BonusCalcApi/V1/Infrastructure/Migrations/20220116175708_AddReportsSentAtToWeek.cs
BonusCalcApi/V1/Infrastructure/Week.cs
BonusCalcApi/V1/UseCase/Interfaces/IUpdateReportsSentAtUseCase.cs
BonusCalcApi/V1/UseCase/UpdateReportSentAtUseCase.cs
BonusCalcApi/V1/UseCase/UpdateReportsSentAtUseCase.cs

The sending of reports may be interrupted so we need to know when all reports have been sent. To facilitate this add a ReportsSentAt attribute to the Week entity which is updated once all reports have been sent via Notify by the frontend application.

Add ReportsSentAt to Week entity

---

BonusCalcApi.Tests/V1/Controllers/OperativesControllerTests.cs
BonusCalcApi.Tests/V1/Controllers/WeeksControllerTests.cs
BonusCalcApi.Tests/V1/UseCase/UpdateOperativeReportSentAtUseCaseTests.cs
BonusCalcApi.Tests/V1/UseCase/UpdateWeekReportsSentAtUseCaseTests.cs
BonusCalcApi/Startup.cs
BonusCalcApi/V1/Controllers/OperativesController.cs
BonusCalcApi/V1/Controllers/WeeksController.cs
BonusCalcApi/V1/UseCase/Interfaces/IUpdateOperativeReportSentAtUseCase.cs
BonusCalcApi/V1/UseCase/Interfaces/IUpdateWeekReportsSentAtUseCase.cs
BonusCalcApi/V1/UseCase/UpdateOperativeReportSentAtUseCase.cs
BonusCalcApi/V1/UseCase/UpdateWeekReportsSentAtUseCase.cs

The `UpdateReportSentAt` and `UpdateReportsSentAt` use cases differ by just the one character so prefix with the entity name to prevent confusion in the future.

Rename use cases to prevent future confusion

---

.circleci/config.yml
BonusCalcApi/serverless.yml

The latest release of the Serverless cli now raise an error for unrecognised options.

Remove invalid --account option for sls command

---

data/migrations/20220124-190000-correct-overtime-pay-elements/README.md
data/migrations/20220124-190000-correct-overtime-pay-elements/apply-work-order-corrections.sql
data/migrations/20220124-190000-correct-overtime-pay-elements/export-work-order-corrections.sql

This is a follow up to #60 and adds the out-of-hours work orders that need to be fixed based on a survey of affected operatives.

Add out-of-hours overtime fix to migration scripts

---

BonusCalcApi.Tests/V1/E2ETests/WeekTests.cs
BonusCalcApi.Tests/V1/Gateways/OutOfHoursSummaryGatewayTests.cs
BonusCalcApi.Tests/V1/Gateways/OvertimeSummaryGatewayTests.cs

This is purely a cosmetic change in the API - the actual figures are set by the listener and the frontend.

Increase the overtime rate from £21.60 to £21.98

---

terraform/production/main.tf
terraform/staging/main.tf

CircleCI failure ([here](https://app.circleci.com/pipelines/github/LBHackney-IT/bonuscalc-api/226/workflows/622334bb-a296-41ea-b344-e09c85a07694/jobs/821)) because postgres has been bumped outside the TF definition - bring back in to line.
No changes for us to be concerned about in this minor version change ([release notes](https://www.postgresql.org/docs/12/release-12-8.html))

Terraform - Minor version bump (DB)

---

data/migrations/20220422-190000-correct-split-work-orders/README.md
data/migrations/20220422-190000-correct-split-work-orders/apply-work-order-corrections.sql
data/migrations/20220422-190000-correct-split-work-orders/export-work-order-corrections.sql

Due to a race condition in the DRS sync some errors were introduced in the bonus calculation for affected work orders. This database removes the existing pay elements for the the affected work orders and creates new ones based on the corrected data from Repairs Hub.

Add data migration to fix errors in split work orders

---

.circleci/config.yml

For some reason unzip didn't need it but openssh-client does.

Auto-confirm installation of packages

---

BonusCalcApi.Tests/V1/UseCase/SupervisorBandDecisionUseCaseTests.cs
BonusCalcApi/V1/UseCase/SupervisorBandDecisionUseCase.cs

For the closing of the 2022/2 period the frontend submitted the correct salary band but for reasons of security the backend ignores the submitted salary band when processing approvals from supervisors. Given that the projected band of fixed band operatives is lower than their actual band then this resulted in quite a few operatives having their salary band lowered. This error has been corrected in the production database and this change will prevent it from happening again.

Use the current salary band when approving fixed band operatives

---

terraform/production/main.tf
terraform/staging/main.tf

- BonusCalc uses a Postgres (RDS) DB to store data
- This is set to automatically update minor versions (AWS does this automatically)
- This leads to a mismatch in the terraform schema over time
So, sync the TF schema with today's reality

Sync minor version - postgres

---

CODEOWNERS

- Removed stale CODEOWNERS file.
- Not a single person who built the application is around anymore. So the CODEOWNERS doesn't have the purpose anymore due to there being no one who'd review the changes from the perspective of in-depth working and/or business knowledge of the repository.

Removed stale CODEOWNERS.

---

.circleci/config.yml

- Added Terraform staging & production state preview to the CCI feature branch workflow.
- Added a Safeguard to prevent staging terraform from applying automatically.
- Added additional Terraform state previews for the `master` branch workflow.
- Renamed the `'any branch'` workflow from `check-development` to `feature-branch-checks`.
- Added the `permit-production-terraform-release` step's missing `master` branch filter.
- We want to know the impact of our Terraform file changes before we merge those changes to the main branch.
- We don't want to staging terraform to apply automatically because occasionally resource's state gets tweaked through the AWS Web UI console, which causes Terraform drift. If left unchanged, Terraform's automatic staging apply would undo any staging environment …

Terraform friendly pipeline

---

terraform/staging/main.tf

- Change staging database `db_engine_version` from "12.14" to "12.17".
- To match the database engine version that's on the cloud.
- Also to trigger the SSL Certificate update done on the **aws-hackney-common-terraform** PR [#68](https://github.com/LBHackney-IT/aws-hackney-common-terraform/pull/68).
- This change **will also trigger the SSL CA Certificate update** from `rds-ca-2019` to `rds-ca-rsa2048-g1`.
Co-authored-by: @Miles-Alford
Co-authored-by: Miles Alford <43789512+Miles-Alford@users.noreply.github.com>

Resolve `staging` Terraform Drift for database engine version.

---

terraform/production/main.tf

- Resolve `production` postgresql database engine version terraform drift.
- Add missing `BackupPolicy` tag to the `production` postgresql database module resource.
- To prevent these from being downgraded/removed whilst re-running TF pipeline to apply the SSL changes _(see notes)_.
- Did these changes primarily to trigger the SSL Certificate update done on the **aws-hackney-common-terraform** PR [#68](https://github.com/LBHackney-IT/aws-hackney-common-terraform/pull/68).
- This change **will trigger the SSL CA Certificate update** from `rds-ca-2019` to `rds-ca-rsa2048-g1`.
- The staging database SSL update was trigger by the PR prior: #113 .
- The development database is not Terraform managed & **[there's no development environment](https://github.com/LBHackney-IT/bonuscalc-api/commit/d96 …

Resolve `production` terraform drift + trigger SSL upgrade (knock-on effect)

---

terraform/staging/main.tf

- Upgrade `staging` bonus-calc postgres database engine version from v12.17 to v16.1.
- Attached a non-default parameter group.
- To save costs by moving away from extended support versions.
- The default postgres 16 parameter group forces ssl for which we're not prepared yet.
- The custom 'postgres16' parameter group is going to be shared by all the databases within the `Housing-Staging` AWS account. So it was created manually due to there being no repository for placing shared housing configuration.

Upgrade `staging` bonus-calc postgres database engine version to v16.

---

terraform/production/main.tf

- Upgrade `production` bonus-calc postgres database engine version from v12.17 to v16.1.
- Attached a non-default parameter group.
- To save costs by moving away from extended support versions.
- The default postgres 16 parameter group forces ssl for which we're not prepared yet.
- The custom 'postgres16' parameter group is going to be shared by all the databases within the `Housing-Production` AWS account. So it was created manually due to there being no repository for placing shared housing configuration.

Upgrade `production` bonus-calc postgres database engine version to v16.

---

.circleci/config.yml
terraform/staging/main.tf

This PR introduces two changes. The first is updating the DB module for staging to match what is on the AWS account thus fixing its drift. The second is updating the ubuntu image on the `build-and-test` job from `2021-04-01` to `2024-11-1` which is the latest image.
To fix the Terraform drift for the DB on the staging environment due to its re-encryption and to ensure the pipeline can run the `build-and-test` job by updating its ubuntu image to a non-deprecated one.

Fix `staging` Terraform drift
